Pull Request for navbar-and-hero
HamzaAnwar1998/MicroversePortofolio pull request #1
Opened 2022-02-10 12:56 UTC by HamzaAnwar1998

navbar created
hero section created
styles applied
media queries applied

2022-02-10 14:06 UTC, Hope1226 requested changes
Hi @HamzaAnwar1998 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
**To Highlight** :1st_place_medal: 
- All linter checks are passed :heavy_check_mark: 
- Great commit messages :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 14:06 UTC, ghost commented on index.html
> +</body>
[REQUIRED] Although I love the design you are implementing :+1: :sunglasses: I have to ask you you to stick to the [chosen template in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122). As a future web developer, you will have to build UI based on the design specified in the technical requirements, let's get used to it from the scratch :relaxed: 

| The design you implemented  | Original design in [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4) |
| ------------- | ------------- |
| ![Screenshot from 2022-02-10 18-16-14](https://user-images.githubusercontent.com/67608876/153416537-62ee5b5a-d3f6-4f08-9406-8712e1e2cfaa.png) | ![Screenshot from 2022-02-10 18-22-02](https://user-images.githubusercontent.com/67608876/153416756-47d4738e-05a9-46dd-a49a-5222543b524f.png) |

In this particular case, you need to change the followings:

- [ ] Make sure your social icons appear after `headline` and they are aligned accordingly.
- [ ] Please make sure that you are using the font and colours (background and font) defined for the chosen template
- [ ] Please make sure you are setting background image using the `CSS` background-image property sample code:
```CSS
selector {
background-image: url(image_path)
}
```
More on that you can find [here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-02-10 14:06 UTC, ghost commented on index.html
> +        </nav>
[REQUIRED] Please kindly make sure that your `<nav />` element is wrapped within the `<header />` tag, in this way we can make your code-base solid and readable. Once it is done, you can separate 
```HTML 
<h6 class="title"><a href="#">Hamza Anwar</a></h6> 
``` 
from your `<nav />` and place within `<header />`. sample code:

```HTML
<header>
       <h6 class="title"><a href="#">Hamza Anwar</a></h6>
       <nav class="navbar">
            <div class="bars"><i class="fa-solid fa-bars fa-xl"></i></div>
            <div class="links">
                <a href="#">Portofolio</a>
                <a href="#">About</a>
                <a href="#">Contact</a>
                <a href="#"><i class="fa-solid fa-envelope fa-xl"></i></a>
            </div>
        </nav>
</header>
```

2022-02-10 14:06 UTC, ghost commented on index.html
> +    <div class="wrapper">
[REQUIRED] Please prefer [sementic tags](https://developer.mozilla.org/en-US/docs/Glossary/Semantics) over divs as much as possible to improve the document's `accessibility`. `<main />` can be the optimal option here.

2022-02-10 14:06 UTC, Hope1226 commented on index.html
> +                </div>
[REQUIRED] Please kindly use the `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag). Please refer to the comment about [Sementics](https://developer.mozilla.org/en-US/docs/Glossary/Semantics) to discover why.

2022-02-10 16:22 UTC, HamzaAnwar1998 commented on index.html
> +</body>
What do you mean by font and colors defined? Are you asking me to use CSS variables?

2022-02-10 16:45 UTC, ghost commented on index.html
> +</body>
the font and colours (background and font) specific to your template in Figma. In this case, just make sure you have the respective background image and you may consider giving a bit more `line-height` to your `<p />` element, and the last one is you need to work on the layout just to make sure your social icons are presented after headline just like it is int the template. good luck!

2022-02-11 08:57 UTC, ShoiraTa approved these changes
### **STATUS: APPROVED  ✔️** 
------
Hi @HamzaAnwar1998 ,  

Your project is complete! Great job working on requested changes 🥇
There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 09:51 UTC, merged